package Model;

/**
 * Created by yangfeng on 27/3/17.
 */
public enum PieceType {
     BREAKPATH, TREASURE, STARTPOINT,PATH0,PATH1,PATH2,PATH3,PATH4,PATH5,PATH6,PATH7,PATH8, GOLD, STONE, BLANK, RIVER, P1,P2,P3,P4,P5,P6,
     DISCARD, MARGIN, DISCARDSIGN,PEEK, PEEKIDENTITY, NEWHANDCARD, PEEKTREASURE, SKIPTURN
}